import { RowKey } from './types';

export enum FloatControlRawHeader {
  Adc1 = 'ADC1',
  Adc2 = 'ADC2',
  Ah = 'Ah',
  AhCharged = 'Ah Charged',
  Altitude = 'Altitude(m)',
  BmsFault = 'BMS-Fault',
  BmsTemp = 'T-BMS',
  BmsTempBattery = 'T-Battery',
  CurrentBattery = 'I-Battery',
  CurrentBooster = 'I-Booster',
  CurrentFieldWeakening = 'I-FldWeak',
  CurrentMotor = 'I-Motor',
  DistanceKm = 'Distance(km)',
  DistanceMi = 'Distance(mi)',
  Duty = 'Duty%',
  Erpm = 'ERPM',
  GpsAccuracy = 'GPS-Accuracy',
  GpsLatitude = 'GPS-Lat',
  GpsLongitude = 'GPS-Long',
  MotorFault = 'Motor-Fault',
  Pitch = 'Pitch',
  RequestedAmps = 'Requested Amps',
  Roll = 'Roll',
  Setpoint = 'Setpoint',
  SetpointAtr = 'SP-ATR',
  SetpointBreakTilt = 'SP-BrkTlt',
  SetpointCarve = 'SP-Carve',
  SetpointRemote = 'SP-Remote',
  SetpointTorqueTilt = 'SP-TrqTlt',
  SpeedKm = 'Speed(km/h)',
  SpeedMi = 'Speed(mph)',
  State = 'State',
  StateRaw = 'State(num)',
  TempBattery = 'T-Batt',
  TempMosfet = 'T-Mosfet',
  TempMotor = 'T-Mot',
  Time = 'Time(s)',
  TruePitch = 'True Pitch',
  Voltage = 'Voltage',
  Wh = 'Wh',
  WhCharged = 'Wh Charged',
}

export const floatControlKeyMap: Record<FloatControlRawHeader, RowKey> = {
  [FloatControlRawHeader.Adc1]: RowKey.Adc1,
  [FloatControlRawHeader.Adc2]: RowKey.Adc2,
  [FloatControlRawHeader.Ah]: RowKey.Ah,
  [FloatControlRawHeader.AhCharged]: RowKey.AhCharged,
  [FloatControlRawHeader.Altitude]: RowKey.Altitude,
  [FloatControlRawHeader.BmsFault]: RowKey.BmsFault,
  [FloatControlRawHeader.BmsTemp]: RowKey.BmsTemp,
  [FloatControlRawHeader.BmsTempBattery]: RowKey.BmsTempBattery,
  [FloatControlRawHeader.CurrentBattery]: RowKey.CurrentBattery,
  [FloatControlRawHeader.CurrentBooster]: RowKey.CurrentBooster,
  [FloatControlRawHeader.CurrentFieldWeakening]: RowKey.CurrentFieldWeakening,
  [FloatControlRawHeader.CurrentMotor]: RowKey.CurrentMotor,
  [FloatControlRawHeader.DistanceKm]: RowKey.Distance,
  [FloatControlRawHeader.DistanceMi]: RowKey.Distance,
  [FloatControlRawHeader.Duty]: RowKey.Duty,
  [FloatControlRawHeader.Erpm]: RowKey.Erpm,
  [FloatControlRawHeader.GpsAccuracy]: RowKey.GpsAccuracy,
  [FloatControlRawHeader.GpsLatitude]: RowKey.GpsLatitude,
  [FloatControlRawHeader.GpsLongitude]: RowKey.GpsLongitude,
  [FloatControlRawHeader.MotorFault]: RowKey.MotorFault,
  [FloatControlRawHeader.Pitch]: RowKey.Pitch,
  [FloatControlRawHeader.RequestedAmps]: RowKey.RequestedAmps,
  [FloatControlRawHeader.Roll]: RowKey.Roll,
  [FloatControlRawHeader.Setpoint]: RowKey.Setpoint,
  [FloatControlRawHeader.SetpointAtr]: RowKey.SetpointAtr,
  [FloatControlRawHeader.SetpointBreakTilt]: RowKey.SetpointBreakTilt,
  [FloatControlRawHeader.SetpointCarve]: RowKey.SetpointCarve,
  [FloatControlRawHeader.SetpointRemote]: RowKey.SetpointRemote,
  [FloatControlRawHeader.SetpointTorqueTilt]: RowKey.SetpointTorqueTilt,
  [FloatControlRawHeader.SpeedKm]: RowKey.Speed,
  [FloatControlRawHeader.SpeedMi]: RowKey.Speed,
  [FloatControlRawHeader.State]: RowKey.State,
  [FloatControlRawHeader.StateRaw]: RowKey.StateRaw,
  [FloatControlRawHeader.TempBattery]: RowKey.TempBattery,
  [FloatControlRawHeader.TempMosfet]: RowKey.TempMosfet,
  [FloatControlRawHeader.TempMotor]: RowKey.TempMotor,
  [FloatControlRawHeader.Time]: RowKey.Time,
  [FloatControlRawHeader.TruePitch]: RowKey.TruePitch,
  [FloatControlRawHeader.Voltage]: RowKey.Voltage,
  [FloatControlRawHeader.Wh]: RowKey.Wh,
  [FloatControlRawHeader.WhCharged]: RowKey.WhCharged,
};
