import { RowKey, type Row } from './types';

export enum VescToolHeader {
  AccX = 'accX',
  AccY = 'accY',
  AccZ = 'accZ',
  AmpHoursCharged = 'amp_hours_charged',
  AmpHoursChargedSetup = 'amp_hours_charged_setup',
  AmpHoursSetup = 'amp_hours_setup',
  AmpHoursUsed = 'amp_hours_used',
  BatteryLevel = 'battery_level',
  BatteryWhTot = 'battery_wh_tot',
  CurrentIn = 'current_in',
  CurrentInSetup = 'current_in_setup',
  CurrentMotor = 'current_motor',
  CurrentMotorSetup = 'current_motor_setup',
  DAxisCurrent = 'd_axis_current',
  DAxisVoltage = 'd_axis_voltage',
  DutyCycle = 'duty_cycle',
  EncoderPosition = 'encoder_position',
  Erpm = 'erpm',
  FaultCode = 'fault_code',
  GnssAlt = 'gnss_alt',
  GnssGVel = 'gnss_gVel',
  GnssHAcc = 'gnss_hAcc',
  GnssLat = 'gnss_lat',
  GnssLon = 'gnss_lon',
  GnssPosTime = 'gnss_posTime',
  GnssVAcc = 'gnss_vAcc',
  GnssVVel = 'gnss_vVel',
  GyroX = 'gyroX',
  GyroY = 'gyroY',
  GyroZ = 'gyroZ',
  InputVoltage = 'input_voltage',
  MsToday = 'ms_today',
  MsTodayImu = 'ms_today_imu',
  MsTodaySetup = 'ms_today_setup',
  NumVescs = 'num_vescs',
  Pitch = 'pitch',
  QAxisCurrent = 'q_axis_current',
  QAxisVoltage = 'q_axis_voltage',
  Roll = 'roll',
  SpeedMetersPerSec = 'speed_meters_per_sec',
  TachoAbsMeters = 'tacho_abs_meters',
  Tachometer = 'tachometer',
  TachometerAbs = 'tachometer_abs',
  TachoMeters = 'tacho_meters',
  TempMos_1 = 'temp_mos_1',
  TempMos_2 = 'temp_mos_2',
  TempMos_3 = 'temp_mos_3',
  TempMosMax = 'temp_mos_max',
  TempMotor = 'temp_motor',
  VescId = 'vesc_id',
  WattHoursCharged = 'watt_hours_charged',
  WattHoursChargedSetup = 'watt_hours_charged_setup',
  WattHoursSetup = 'watt_hours_setup',
  WattHoursUsed = 'watt_hours_used',
  Yaw = 'yaw',
}

type VescValues = (typeof vescToolToRowMap)[VescToolHeader];
export type RequiredRowValues = NonNullable<
  {
    [k in keyof Row]: undefined extends Row[k] ? never : k extends VescValues ? never : k;
  }[keyof Row]
>;

export const vescToolToRowMap = {
  [VescToolHeader.AccX]: undefined,
  [VescToolHeader.AccY]: undefined,
  [VescToolHeader.AccZ]: undefined,
  [VescToolHeader.AmpHoursCharged]: RowKey.AhCharged,
  [VescToolHeader.AmpHoursChargedSetup]: undefined,
  [VescToolHeader.AmpHoursSetup]: undefined,
  [VescToolHeader.AmpHoursUsed]: RowKey.Ah,
  [VescToolHeader.BatteryLevel]: undefined,
  [VescToolHeader.BatteryWhTot]: undefined,
  [VescToolHeader.CurrentIn]: RowKey.CurrentBattery,
  [VescToolHeader.CurrentInSetup]: undefined,
  [VescToolHeader.CurrentMotor]: RowKey.CurrentMotor,
  [VescToolHeader.CurrentMotorSetup]: undefined,
  [VescToolHeader.DAxisCurrent]: undefined,
  [VescToolHeader.DAxisVoltage]: undefined,
  [VescToolHeader.DutyCycle]: RowKey.Duty,
  [VescToolHeader.EncoderPosition]: undefined,
  [VescToolHeader.Erpm]: RowKey.Erpm,
  [VescToolHeader.FaultCode]: RowKey.MotorFault,
  [VescToolHeader.GnssAlt]: RowKey.Altitude,
  [VescToolHeader.GnssGVel]: undefined,
  [VescToolHeader.GnssHAcc]: RowKey.GpsAccuracy,
  [VescToolHeader.GnssLat]: RowKey.GpsLatitude,
  [VescToolHeader.GnssLon]: RowKey.GpsLongitude,
  [VescToolHeader.GnssPosTime]: undefined,
  [VescToolHeader.GnssVAcc]: undefined,
  [VescToolHeader.GnssVVel]: undefined,
  [VescToolHeader.GyroX]: undefined,
  [VescToolHeader.GyroY]: undefined,
  [VescToolHeader.GyroZ]: undefined,
  [VescToolHeader.InputVoltage]: RowKey.Voltage,
  [VescToolHeader.MsToday]: RowKey.Time,
  [VescToolHeader.MsTodayImu]: undefined,
  [VescToolHeader.MsTodaySetup]: undefined,
  [VescToolHeader.NumVescs]: undefined,
  [VescToolHeader.Pitch]: RowKey.Pitch,
  [VescToolHeader.QAxisCurrent]: undefined,
  [VescToolHeader.QAxisVoltage]: undefined,
  [VescToolHeader.Roll]: RowKey.Roll,
  [VescToolHeader.SpeedMetersPerSec]: RowKey.Speed,
  [VescToolHeader.TachoAbsMeters]: undefined,
  [VescToolHeader.Tachometer]: undefined,
  [VescToolHeader.TachometerAbs]: undefined,
  [VescToolHeader.TachoMeters]: undefined,
  [VescToolHeader.TempMos_1]: undefined,
  [VescToolHeader.TempMos_2]: undefined,
  [VescToolHeader.TempMos_3]: undefined,
  [VescToolHeader.TempMosMax]: RowKey.TempMosfet,
  [VescToolHeader.TempMotor]: RowKey.TempMotor,
  [VescToolHeader.VescId]: undefined,
  [VescToolHeader.WattHoursCharged]: RowKey.WhCharged,
  [VescToolHeader.WattHoursChargedSetup]: undefined,
  [VescToolHeader.WattHoursSetup]: undefined,
  [VescToolHeader.WattHoursUsed]: RowKey.Wh,
  [VescToolHeader.Yaw]: undefined,
} satisfies Record<VescToolHeader, RowKey | undefined>;
