name: Deploy to Pages

on:
  push:
    branches: ['master']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  pages: write
  id-token: write
  # GitHub Pages only needs `read`, but we have `write` so we can push commits
  contents: write

# Allow only one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Checks
        run: npm run checks

  deploy:
    needs: ['checks']
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Bump version
        run: |
          npm run ci:bump
          npm i --package-lock-only
      - name: Build
        run: VITE_BUILD_VERSION="$(jq -r .version ./package.json)-$(git rev-parse --short HEAD)" npm run build
      - name: Push back
        run: |
          git config --global user.name  "float-view-ci"
          git config --global user.email "acheronfail+float-view-ci@gmail.com"
          git add package.json package-lock.json
          git commit --no-verify --message "[skip ci] ci version bump"
          git pull --rebase
          git push
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
